[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.json"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"
